services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - chrome-server
    command: rails s -b 0.0.0.0
  chrome-server:
    image: seleniarm/standalone-chromium:latest
